config:
  api_url: 'apiurl' # https://api.example.com/api/v2/fn/ps/update
  api_key: 'apikey' # 设置的key
  report_time: '10' # 上报时间间隔，单位秒
  keywords: # 关键词屏蔽，数组形式
    - 'pronhub'

  # replace的第一行与replace_to的第一行对应，以此类推，msedge会被替换为Chrome，idea64会被替换为Code
  replace:
    - 'msedge'
    - 'idea64'
  replace_to:
    - 'Chrome'
    - 'Code'
